// State for user 
const indiaStates = [
  { code: "AP", name: "andhra pradesh" },
  { code: "AR", name: "arunachal pradesh" },
  { code: "AS", name: "assam" },
  { code: "BR", name: "bihar" },
  { code: "CG", name: "chhattisgarh" },
  { code: "GA", name: "goa" },
  { code: "GJ", name: "gujarat" },
  { code: "HR", name: "haryana" },
  { code: "HP", name: "himachal pradesh" },
  { code: "JH", name: "jharkhand" },
  { code: "KA", name: "karnataka" },
  { code: "KL", name: "kerala" },
  { code: "MP", name: "madhya pradesh" },
  { code: "MH", name: "maharashtra" },
  { code: "MN", name: "manipur" },
  { code: "ML", name: "meghalaya" },
  { code: "MZ", name: "mizoram" },
  { code: "NL", name: "nagaland" },
  { code: "OD", name: "odisha" },
  { code: "PB", name: "punjab" },
  { code: "RJ", name: "rajasthan" },
  { code: "SK", name: "sikkim" },
  { code: "TN", name: "tamil nadu" },
  { code: "TG", name: "telangana" },
  { code: "TR", name: "tripura" },
  { code: "UP", name: "uttar pradesh" },
  { code: "UK", name: "uttarakhand" },
  { code: "WB", name: "west bengal" },

  // Union Territories
  { code: "AN", name: "andaman and nicobar islands" },
  { code: "CH", name: "chandigarh" },
  { code: "DN", name: "dadra and nagar haveli and daman and diu" },
  { code: "DL", name: "delhi" },
  { code: "JK", name: "jammu and kashmir" },
  { code: "LA", name: "ladakh" },
  { code: "LD", name: "lakshadweep" },
  { code: "PY", name: "puducherry" }
];

// District
const upDistricts = [
  { name: "agra" },
  { name: "aligarh" },
  { name: "ambedkar nagar" },
  { name: "amethi" },
  { name: "amroha" },
  { name: "auraiya" },
  { name: "ayodhya" },
  { name: "azamgarh" },
  { name: "baghpat" },
  { name: "bahraich" },
  { name: "ballia" },
  { name: "balrampur" },
  { name: "banda" },
  { name: "barabanki" },
  { name: "bareilly" },
  { name: "basti" },
  { name: "bhadohi" },
  { name: "bijnor" },
  { name: "budaun" },
  { name: "bulandshahr" },
  { name: "chandauli" },
  { name: "chitrakoot" },
  { name: "deoria" },
  { name: "etah" },
  { name: "etawah" },
  { name: "farrukhabad" },
  { name: "fatehpur" },
  { name: "firozabad" },
  { name: "gautam buddha nagar" },
  { name: "ghaziabad" },
  { name: "ghazipur" },
  { name: "gonda" },
  { name: "gorakhpur" },
  { name: "hamirpur" },
  { name: "hapur" },
  { name: "hardoi" },
  { name: "hathras" },
  { name: "jalaun" },
  { name: "jaunpur" },
  { name: "jhansi" },
  { name: "kannauj" },
  { name: "kanpur dehat" },
  { name: "kanpur nagar" },
  { name: "kasganj" },
  { name: "kaushambi" },
  { name: "kheri (lakhimpur kheri)" },
  { name: "kushinagar" },
  { name: "lalitpur" },
  { name: "lucknow" },
  { name: "maharajganj" },
  { name: "mahoba" },
  { name: "mainpuri" },
  { name: "mathura" },
  { name: "mau" },
  { name: "meerut" },
  { name: "mirzapur" },
  { name: "moradabad" },
  { name: "muzaffarnagar" },
  { name: "pilibhit" },
  { name: "pratapgarh" },
  { name: "prayagraj" },
  { name: "raebareli" },
  { name: "rampur" },
  { name: "saharanpur" },
  { name: "sambhal" },
  { name: "sant kabir nagar" },
  { name: "shahjahanpur" },
  { name: "shamli" },
  { name: "shravasti" },
  { name: "siddharthnagar" },
  { name: "sitapur" },
  { name: "sonbhadra" },
  { name: "sultanpur" },
  { name: "unnao" },
  { name: "varanasi" }
];

module.exports = {
  indiaStates,
  upDistricts
};